kind: Pod
apiVersion: v1
metadata:
    name: demo-grpc-client-cli-go
    labels:
        name: demo-grpc-client-cli-go
        app: demo-grpc
spec:
    restartPolicy: OnFailure
    containers:
        - name: main
          resources:
              limits: {}
          args: ["--host=demo-grpc-server"]
          image: sevendollar/demo-grpc-client-cli-go
          imagePullPolicy: Always
