kind: Service
apiVersion: v1
metadata:
    name: demo-grpc-server
    labels:
        name: demo-grpc-server
        app: demo-grpc
spec:
    clusterIP: None
    selector:
        name: demo-grpc-server
        app: demo-grpc
    ports:
        - name: grpc
          port: 50051
          targetPort: grpc
